### ISSUE TITLE
The bot, sometimes, does not resume playback once I have joined the server again.

### ISSUE THREAD

**Issue by DaleJV** [moonstar-x/discord-music-24-7#64] opened 2022-01-28 20:53 UTC
#### :bug: Describe the Bug

> Most of the time, when I join the voice channel that has the bot sitting alone it in, the playback does not resume. I have to leave again and join for it to start playing. Yet, in the console it states that the presence has bene updated and the music has been resumed after I join. Very rarely will it properly resume playback once I join

#### :pencil2: Steps to Reproduce

> 1 - Get everyone to leave the voice channel
> 2 - Get one person to join back in
> 3 - The console will say music has been resumed and presence updated yet no music will be playing

#### :confused: Expected Behavior

> In terms of the expected behavior, the bot should resume playback and actually play the song. 

#### :scroll: Log

``` text
(12:51:08 PM) - [INFO] -  User LlamaLoops has joined 🎧᲼24/7 lofi radio (LL).
(12:51:08 PM) - [INFO] -  Music has been resumed.
(12:51:08 PM) - [INFO] -  Presence updated to: ► nostalgic disney songs but its lofi extended version (2 hours)
```

#### :camera: Screenshots

> N/A

#### :question: Other Information

* Node Version: `Version of the node runtime.`
v16.13.2

**Comment by moonstar-x** [comment] 2022-01-28 20:56
Hey there sorry that this is happening.

I'm going to update the bot soon to use the latest discord.js which should have some improvements on how voice works.

Hopefully this improves the resume behavior when pausing/unpausing the stream.

**Comment by DaleJV** [comment] 2022-01-28 21:05
Thank you for the prompt reply and provided resolution, I appreciate that a lot!

Let me know when you have updated discord.js and I will test it for you!

**Comment by DaleJV** [comment] 2022-02-04 03:22
To fix this, change the `pause_on_empty` command to `false`.

**Comment by DaleJV** [comment] 2022-02-04 03:31
In terms of resource consumption, it uses almost no network resources (less than 0.1 Mbps). Even with pause enabled, my bot is being used most of the day.

**Comment by moonstar-x** [comment] 2022-07-27 05:20
![](https://github.trello.services/images/mini-trello-icon.png) [Bot might not resume playback when people join back to the channel.](https://trello.com/c/nJaUWD7d/44-bot-might-not-resume-playback-when-people-join-back-to-the-channel)

**Comment by moonstar-x** [comment] 2022-07-27 05:26
Hi there, sorry for the long hiatus, I'm trying to make some time during my week for these things.

After some thought it seems that this might be caused by #76 which is a duplicate of #56 so I'm closing this issue.

**Closed by moonstar-x** 2022-07-27 05:26 UTC
Labels: Type: Bug
